/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#b7b5b4",
        "surface-dim": "#131313",
        tertiary: "#ffffff",
        surface: "#131313",
        "on-error-container": "#ffdad6",
        "on-background": "#e2e2e2",
        "primary-fixed": "#e2e2e2",
        secondary: "#c8c6c5",
        "secondary-fixed-dim": "#c8c6c5",
        "error-container": "#93000a",
        "surface-bright": "#393939",
        "on-tertiary-container": "#656464",
        "outline-variant": "#444748",
        "primary-fixed-dim": "#c6c6c7",
        primary: "#ffffff",
        error: "#ffb4ab",
        "on-secondary": "#313030",
        "surface-variant": "#353535",
        "on-secondary-fixed": "#1c1b1b",
        "on-primary-fixed-variant": "#454747",
        "inverse-primary": "#5d5f5f",
        "tertiary-container": "#e5e2e1",
        "secondary-fixed": "#e5e2e1",
        background: "#060606",
        "surface-tint": "#c6c6c7",
        "secondary-container": "#474746",
        outline: "#8e9192",
        "on-surface-variant": "#c4c7c8",
        "surface-container-low": "#1b1b1b",
        "on-tertiary": "#313030",
        "on-primary": "#2f3131",
        "surface-container-high": "#2a2a2a",
        "on-surface": "#e2e2e2",
        "surface-container-lowest": "#0e0e0e",
        "primary-container": "#e2e2e2",
        "on-secondary-fixed-variant": "#474746",
        "surface-container": "#1f1f1f",
        "on-tertiary-fixed": "#1c1b1b",
        "inverse-on-surface": "#303030",
        "inverse-surface": "#e2e2e2",
        "tertiary-fixed": "#e5e2e1",
        "on-tertiary-fixed-variant": "#474646",
        "tertiary-fixed-dim": "#c9c6c5",
        "on-primary-fixed": "#1a1c1c",
        "on-primary-container": "#636565",
        "on-error": "#690005",
        "surface-container-highest": "#353535",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1.5rem",
        "3xl": "2rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1440px",
        "margin-desktop": "80px",
        gutter: "32px",
        unit: "8px",
        "section-gap": "160px",
        "margin-mobile": "24px",
      },
      fontFamily: {
        "label-mono": ["var(--font-jetbrains-mono)", "monospace"],
        "body-lg": ["var(--font-hanken-grotesk)", "sans-serif"],
        "headline-lg": ["var(--font-sora)", "sans-serif"],
        "body-md": ["var(--font-hanken-grotesk)", "sans-serif"],
        "display-hero": ["var(--font-sora)", "sans-serif"],
        "headline-md": ["var(--font-sora)", "sans-serif"],
        "display-hero-mobile": ["var(--font-sora)", "sans-serif"],
      },
      fontSize: {
        "label-mono": [
          "12px",
          { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "500" },
        ],
        "body-lg": ["20px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg": [
          "48px",
          { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-hero": [
          "96px",
          { lineHeight: "1.0", letterSpacing: "-0.04em", fontWeight: "800" },
        ],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "display-hero-mobile": [
          "48px",
          { lineHeight: "1.1", letterSpacing: "-0.03em", fontWeight: "800" },
        ],
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};
